### PR TITLE
v2.8.x. CSHARP-2582: Decimal128 to decimal conversion loses precision for zero.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**

### CODE REVIEW

**Comment by DmitryLukyanov** [comment]
Evergreen: https://evergreen.mongodb.com/version/5ccc8aa1d6d80a1d24bcbdb7

**Review by rstam — APPROVED** [review]
I assume this is just a cherry-pick with no changes at all from master?

**Comment by DmitryLukyanov** [comment]
Yes, you are right

**Review by vincentkam — APPROVED** [review]
LGTM! 😸

**Pull request closed without merging**
