### PR TITLE
CSHARP-3025: Update comment in Transactions withTxn examples for the manual.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**
Just small documentation change

### CODE REVIEW

**Review by rstam — APPROVED** [review]
LGTM

No tests? :)

**Review by MikalaiMazurenka — APPROVED** [review]
LGTM

**Comment by DmitryLukyanov** [comment]
> No tests? :)

it will be too much effort :)

**Review by vincentkam — APPROVED** [review]
LGTM! 😸

**Pull request closed without merging**
