### PR TITLE
CSHARP-3257: Fix TestMax test.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**
EG: https://evergreen.mongodb.com/version/5fc6471357e85a4299bbb897

### CODE REVIEW

**Review by MikalaiMazurenka — APPROVED** [review]
I'd suggest to remove the dot from commit message

**Comment by DmitryLukyanov** [comment]
> 
> 
> I'd suggest to remove the dot from commit message

as far as I know, mostly(not always but still) we set `dot` at the end of commit messages

**Review by rstam — APPROVED** [review]
LGTM

**Review by JamesKovacs — COMMENTED** [review]
LGTM

**Pull request closed without merging**
