### PR TITLE
CSHARP-2410: Bump wire protocol version for 4.2.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**
Evergreen: https://evergreen.mongodb.com/version/5cbe3991306615107b262f62

### CODE REVIEW

**Review by jyemin — COMMENTED** [review]
Seems like this should cause a test to fail, like "SupportedWireVersionRange_should_return_expected_result()" in ClusterTests.cs.

**Comment by DmitryLukyanov** [comment]
>Seems like this should cause a test to fail

Before I run evergreen tests, but didn't have a chance to check their results.
Now, I've fixed `SupportedWireVersionRange_should_return_expected_result`.

**Review by jyemin — APPROVED** [review]
LGTM

**Review by rstam — APPROVED** [review]

**Review by vincentkam — APPROVED** [review]
LGTM 😺

**Pull request closed without merging**
