### PR TITLE
CSHARP-2680: Add [Beta] flags for public FLE classes/methods/properties. Add release notes for 2.10.0-beta1.

### PR DESCRIPTION
**Pull request by DmitryLukyanov**

### CODE REVIEW

**Comment by rstam** [comment]
Be careful when squashing and rebasing, your commit comment has the wrong JIRA ticket number.

**Review by rstam — APPROVED** [review]
Other than fixing the JIRA ticket number in the commit comment LGTM

**Comment by DmitryLukyanov** [comment]
Jira number is fixed

**Review by vincentkam — APPROVED** [review]
LGTM 😺 !

**Pull request closed without merging**
